name: Ascend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:


  flutter:
    sdk: flutter
  country_picker: ^2.0.27
  animated_button: ^0.3.1
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  carousel_slider: ^5.1.1
  change_app_package_name: ^1.1.0
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.6.1
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.0
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.0.0
  fluttertoast: ^8.2.4
  go_router: ^16.2.4
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hexcolor: ^3.0.1
  http: ^1.1.0
  im_stepper: ^1.0.1
  intl: ^0.20.2
  intl_phone_field: ^3.1.0
  lottie: 3.3.1
  marquee_widget: ^1.2.0
  mysql1: ^0.20.0
  particles_flutter: ^0.1.4
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  shelf: ^1.4.0
  shimmer_animation: ^2.1.0
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  video_player: ^2.7.2
  webview_flutter: ^4.11.0
  # dropdown_button2: ^2.3.9
  # change_app_package_name: ^1.1.0
  phone_number: ^2.0.1
  phone_numbers_parser: ^8.1.0
  image_picker: ^1.2.0
  image_cropper: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/Auth/select_account/
    - assets/images/Auth/location/
    - assets/

  fonts:
    - family: SF-Pro-Display-Heavy
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
    - family: SF-Pro-Rounded-Black
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Black.otf
    - family: SF-Pro-Rounded-Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
    - family: SF-Pro-Text-Black
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
    - family: SF-Pro-Text-Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
flutter_intl:
  enabled: true
